/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ZCounter: typeof import('./components/ZCounter.vue')['default']
    ZFooter: typeof import('./components/ZFooter.vue')['default']
    ZInput: typeof import('./components/ZInput.vue')['default']
    ZLogo: typeof import('./components/ZLogo.vue')['default']
  }
}
